/** YuwpUI 1.4.24-yuspplus Copyright © 2017-present Yusys All Rights Reserved. */
/* Automatically generated by './build/bin/build-entry.js' */

import Pagination from '../packages/pagination/index.js';
import Dialog from '../packages/dialog/index.js';
import Autocomplete from '../packages/autocomplete/index.js';
import Dropdown from '../packages/dropdown/index.js';
import DropdownMenu from '../packages/dropdown-menu/index.js';
import DropdownItem from '../packages/dropdown-item/index.js';
import Menu from '../packages/menu/index.js';
import Submenu from '../packages/submenu/index.js';
import MenuItem from '../packages/menu-item/index.js';
import MenuItemGroup from '../packages/menu-item-group/index.js';
import Input from '../packages/input/index.js';
import InputNumber from '../packages/input-number/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import Switch from '../packages/switch/index.js';
import Select from '../packages/select/index.js';
import Option from '../packages/option/index.js';
import OptionGroup from '../packages/option-group/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Table from '../packages/table/index.js';
import TableColumn from '../packages/table-column/index.js';
import DatePicker from '../packages/date-picker/index.js';
import TimeSelect from '../packages/time-select/index.js';
import TimePicker from '../packages/time-picker/index.js';
import Popover from '../packages/popover/index.js';
import Tooltip from '../packages/tooltip/index.js';
import MessageBox from '../packages/message-box/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import BreadcrumbItem from '../packages/breadcrumb-item/index.js';
import Form from '../packages/form/index.js';
import FormItem from '../packages/form-item/index.js';
import Tabs from '../packages/tabs/index.js';
import TabPane from '../packages/tab-pane/index.js';
import Tag from '../packages/tag/index.js';
import Tree from '../packages/tree/index.js';
import Alert from '../packages/alert/index.js';
import Notification from '../packages/notification/index.js';
import Slider from '../packages/slider/index.js';
import Loading from '../packages/loading/index.js';
import Icon from '../packages/icon/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Upload from '../packages/upload/index.js';
import Progress from '../packages/progress/index.js';
import Spinner from '../packages/spinner/index.js';
import Message from '../packages/message/index.js';
import Badge from '../packages/badge/index.js';
import Card from '../packages/card/index.js';
import Rate from '../packages/rate/index.js';
import Steps from '../packages/steps/index.js';
import Step from '../packages/step/index.js';
import Carousel from '../packages/carousel/index.js';
import CascaderPanel from '../packages/cascader-panel/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import CarouselItem from '../packages/carousel-item/index.js';
import Collapse from '../packages/collapse/index.js';
import CollapseItem from '../packages/collapse-item/index.js';
import Cascader from '../packages/cascader/index.js';
import ColorPicker from '../packages/color-picker/index.js';
import Transfer from '../packages/transfer/index.js';
import Lazy from '../packages/lazy/index.js';
import ComboTable from '../packages/combo-table/index.js';
import ComboTree from '../packages/combo-tree/index.js';
import Echarts from '../packages/echarts/index.js';
import Timeline from '../packages/timeline/index.js';
import TimelineItem from '../packages/timelineItem/index.js';
import Link from '../packages/link/index.js';
import Header from '../packages/header/index.js';
import Container from '../packages/container/index.js';
import Aside from '../packages/aside/index.js';
import Main from '../packages/main/index.js';
import Footer from '../packages/footer/index.js';
import Drawer from '../packages/drawer/index.js';
import InfiniteScroll from '../packages/infinite-scroll/index.js';
import Backtop from '../packages/backtop/index.js';
import Image from '../packages/image/index.js';
import Calendar from '../packages/calendar/index.js';
import Divider from '../packages/divider/index.js';
import Avatar from '../packages/avatar/index.js';
import XformQ from '../packages/xform-q/index.js';
import XformX from '../packages/xform-x/index.js';
import XtableX from '../packages/xtable-x/index.js';
import Xdialog from '../packages/xdialog/index.js';
import Xtree from '../packages/xtree/index.js';
import Xselect from '../packages/xselect/index.js';
import Xradio from '../packages/xradio/index.js';
import Xcheckbox from '../packages/xcheckbox/index.js';
import Xcascader from '../packages/xcascader/index.js';
import Xtable from '../packages/xtable/index.js';
import XtableColumn from '../packages/xtable-column/index.js';
import XdynamicForm from '../packages/xdynamic-form/index.js';
import Xform from '../packages/xform/index.js';
import XformGroup from '../packages/xform-group/index.js';
import XformItem from '../packages/xform-item/index.js';
import XformItemPart from '../packages/xform-item-part/index.js';
import XsplitScreen from '../packages/xsplit-screen/index.js';
import XsplitScreenItem from '../packages/xsplit-screen-item/index.js';
import LinkageSelect from '../packages/linkage-select/index.js';
import Norepeat from '../packages/norepeat/index.js';
import Num from '../packages/num/index.js';
import Xcalender from '../packages/xcalender/index.js';
import Anchor from '../packages/anchor/index.js';
import AnchorLink from '../packages/anchor-link/index.js';
import AvatarList from '../packages/avatar-list/index.js';
import CountDown from '../packages/count-down/index.js';
import Range from '../packages/range/index.js';
import CitySelect from '../packages/city-select/index.js';
import Countup from '../packages/countup/index.js';
import TagOption from '../packages/tag-option/index.js';
import TagSelect from '../packages/tag-select/index.js';
import PageAssist from '../packages/page-assist/index.js';
import Panel from '../packages/panel/index.js';
import ButtonDrop from '../packages/button-drop/index.js';
import locale from '@/src/locale';
import CollapseTransition from '@/src/transitions/collapse-transition';

const components = [
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  CascaderPanel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  Lazy,
  ComboTable,
  ComboTree,
  Echarts,
  Timeline,
  TimelineItem,
  Link,
  Header,
  Container,
  Aside,
  Main,
  Footer,
  Drawer,
  InfiniteScroll,
  Backtop,
  Image,
  Calendar,
  Divider,
  Avatar,
  XformQ,
  XformX,
  XtableX,
  Xdialog,
  Xtree,
  Xselect,
  Xradio,
  Xcheckbox,
  Xcascader,
  Xtable,
  XtableColumn,
  XdynamicForm,
  Xform,
  XformGroup,
  XformItem,
  XformItemPart,
  XsplitScreen,
  XsplitScreenItem,
  LinkageSelect,
  Num,
  Xcalender,
  Anchor,
  AnchorLink,
  AvatarList,
  CountDown,
  Range,
  CitySelect,
  Countup,
  TagOption,
  TagSelect,
  PageAssist,
  Panel,
  ButtonDrop,
  CollapseTransition
];

window.$YUWPUI_CONF = window.$YUWPUI_CONF || {};
const install = function(Vue, opts = window.$YUWPUI_CONF) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  /*
    组件属性全局配置功能， use时配置{pagination: {small: true, currentPage: 2, total: 10000, pageSize: 100}}格式的参数。
    优先级：组件标签配置的属性 > 全局配置的属性 > 组件默认属性值
  */
  components.forEach(component => {
    var comName = component.xtype.toLowerCase();
    var attrs = component.props;
    Object.keys(opts).forEach(function(name) {
      if (comName.slice(2) === name) {
        Object.keys(opts[name]).forEach(function(attr) {
          if (opts[name][attr] !== undefined && attrs[attr] !== undefined) {
            if (typeof (attrs[attr]) === 'function') {
              attrs[attr] = {default: opts[name][attr]};
            } else {
              attrs[attr].default = opts[name][attr];
            }
          }
        });
      }
    });
    Vue.component(component.name, component);
    Vue.component(component.xtype, component);
  });
  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);
  Vue.use(Norepeat.directive);

  Vue.prototype.$YUFPWP = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$customConfirm = MessageBox.customConfirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}
console.log('YuwpUI 1.4.24-yuspplus.2021-3-23');
export default {
  version: '1.4.24-yuspplus',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Pagination,
  Dialog,
  Autocomplete,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Input,
  InputNumber,
  Radio,
  RadioGroup,
  RadioButton,
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Table,
  TableColumn,
  DatePicker,
  TimeSelect,
  TimePicker,
  Popover,
  Tooltip,
  MessageBox,
  Breadcrumb,
  BreadcrumbItem,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Tree,
  Alert,
  Notification,
  Slider,
  Icon,
  Row,
  Col,
  Upload,
  Progress,
  Spinner,
  Message,
  Badge,
  Card,
  Rate,
  Steps,
  Step,
  Carousel,
  CascaderPanel,
  Scrollbar,
  CarouselItem,
  Collapse,
  CollapseItem,
  Cascader,
  ColorPicker,
  Transfer,
  Lazy,
  ComboTable,
  ComboTree,
  Echarts,
  Timeline,
  TimelineItem,
  Link,
  Header,
  Container,
  Aside,
  Main,
  Footer,
  Drawer,
  InfiniteScroll,
  Backtop,
  Image,
  Calendar,
  Divider,
  Avatar,
  XformQ,
  XformX,
  XtableX,
  Xdialog,
  Xtree,
  Xselect,
  Xradio,
  Xcheckbox,
  Xcascader,
  Xtable,
  XtableColumn,
  XdynamicForm,
  Xform,
  XformGroup,
  XformItem,
  XformItemPart,
  XsplitScreen,
  XsplitScreenItem,
  LinkageSelect,
  Norepeat,
  Num,
  Xcalender,
  Anchor,
  AnchorLink,
  AvatarList,
  CountDown,
  Range,
  CitySelect,
  Countup,
  TagOption,
  TagSelect,
  PageAssist,
  Panel,
  ButtonDrop
};
